
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Azure.Tasks.Batchai
{
     public partial class AzureBatchaiClusterFileTask : ExternalProcessTaskBase<AzureBatchaiClusterFileTask>
     {
        
        /// <summary>
        /// Commands to work with files generated by node setup task.
        /// </summary>
        public AzureBatchaiClusterFileTask()
        {
            WithArguments("az batchai cluster file");
        }

        protected override string Description { get; set; }
        
     }
}
