
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Azure.Tasks.Servicebus
{
     public partial class AzureServicebusQueueAuthorizationRuleKeysRenewTask : ExternalProcessTaskBase<AzureServicebusQueueAuthorizationRuleKeysRenewTask>
     {
        
        /// <summary>
        /// Regenerate keys of Authorization Rule for Service Bus Queue.
        /// </summary>
        public AzureServicebusQueueAuthorizationRuleKeysRenewTask(string key = null ,  string name = null ,  string namespaceName = null ,  string queueName = null ,  string resourceGroup = null)
        {
            WithArguments("az servicebus queue authorization-rule keys renew");
WithArguments("--key");
            if (!string.IsNullOrEmpty(key))
            {
                 WithArguments(key);
            }

WithArguments("--name");
            if (!string.IsNullOrEmpty(name))
            {
                 WithArguments(name);
            }

WithArguments("--namespace-name");
            if (!string.IsNullOrEmpty(namespaceName))
            {
                 WithArguments(namespaceName);
            }

WithArguments("--queue-name");
            if (!string.IsNullOrEmpty(queueName))
            {
                 WithArguments(queueName);
            }

WithArguments("--resource-group");
            if (!string.IsNullOrEmpty(resourceGroup))
            {
                 WithArguments(resourceGroup);
            }

        }

        protected override string Description { get; set; }
        
        /// <summary>
        /// Optional, if the key value provided, is set for KeyType or autogenerated Key value set for keyType.
        /// </summary>
        public AzureServicebusQueueAuthorizationRuleKeysRenewTask KeyValue(string keyValue = null)
        {
            WithArguments("--key-value");
            if (!string.IsNullOrEmpty(keyValue))
            {
                 WithArguments(keyValue);
            }

            return this;
        }
     }
}
