
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Azure.Tasks.Eventhubs
{
     public partial class AzureEventhubsEventhubAuthorizationRuleKeysRenewTask : ExternalProcessTaskBase<AzureEventhubsEventhubAuthorizationRuleKeysRenewTask>
     {
        
        /// <summary>
        /// Regenerate the connection strings of Authorizationrule for the namespace.
        /// </summary>
        public AzureEventhubsEventhubAuthorizationRuleKeysRenewTask(string eventhubName = null ,  string key = null ,  string name = null ,  string namespaceName = null ,  string resourceGroup = null)
        {
            WithArguments("az eventhubs eventhub authorization-rule keys renew");
WithArguments("--eventhub-name");
            if (!string.IsNullOrEmpty(eventhubName))
            {
                 WithArguments(eventhubName);
            }

WithArguments("--key");
            if (!string.IsNullOrEmpty(key))
            {
                 WithArguments(key);
            }

WithArguments("--name");
            if (!string.IsNullOrEmpty(name))
            {
                 WithArguments(name);
            }

WithArguments("--namespace-name");
            if (!string.IsNullOrEmpty(namespaceName))
            {
                 WithArguments(namespaceName);
            }

WithArguments("--resource-group");
            if (!string.IsNullOrEmpty(resourceGroup))
            {
                 WithArguments(resourceGroup);
            }

        }

        protected override string Description { get; set; }
        
        /// <summary>
        /// Optional, if the key value provided, is set for KeyType or autogenerated Key value set for keyType.
        /// </summary>
        public AzureEventhubsEventhubAuthorizationRuleKeysRenewTask KeyValue(string keyValue = null)
        {
            WithArguments("--key-value");
            if (!string.IsNullOrEmpty(keyValue))
            {
                 WithArguments(keyValue);
            }

            return this;
        }
     }
}
