
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Azure.Tasks.Relay
{
     public partial class AzureRelayHycoAuthorizationRuleKeysRenewTask : ExternalProcessTaskBase<AzureRelayHycoAuthorizationRuleKeysRenewTask>
     {
        
        /// <summary>
        /// Regenerate keys of Authorization Rule for Relay Service Hybrid Connection.
        /// </summary>
        public AzureRelayHycoAuthorizationRuleKeysRenewTask(string hybridConnectionName = null ,  string key = null ,  string name = null ,  string namespaceName = null ,  string resourceGroup = null)
        {
            WithArguments("az relay hyco authorization-rule keys renew");
WithArguments("--hybrid-connection-name");
            if (!string.IsNullOrEmpty(hybridConnectionName))
            {
                 WithArguments(hybridConnectionName);
            }

WithArguments("--key");
            if (!string.IsNullOrEmpty(key))
            {
                 WithArguments(key);
            }

WithArguments("--name");
            if (!string.IsNullOrEmpty(name))
            {
                 WithArguments(name);
            }

WithArguments("--namespace-name");
            if (!string.IsNullOrEmpty(namespaceName))
            {
                 WithArguments(namespaceName);
            }

WithArguments("--resource-group");
            if (!string.IsNullOrEmpty(resourceGroup))
            {
                 WithArguments(resourceGroup);
            }

        }

        protected override string Description { get; set; }
        
        /// <summary>
        /// Optional, if the key value provided, is set for KeyType or autogenerated Key value set for keyType.
        /// </summary>
        public AzureRelayHycoAuthorizationRuleKeysRenewTask KeyValue(string keyValue = null)
        {
            WithArguments("--key-value");
            if (!string.IsNullOrEmpty(keyValue))
            {
                 WithArguments(keyValue);
            }

            return this;
        }
     }
}
